### ISSUE TITLE
Node-red-redplc

### ISSUE THREAD

**Issue by DuncanG5** [redplc/redplc#1]
Hello, 

I have started to use you @redplc/node-red-redplc package to start coding with PLC logic on Node-Red.

I have found that the Logic function gates have difficulties on the "AND" and "XOR" settings and default to the "OR" gate. 

After looking through your code I believe that the issue is in the nodes/lib/syslib.js file on line 496 and 499 where you define the cases in lower case ("and"/"xor") instead of uppercase("AND"/"XOR"). This  also needs to be implemented on line 487 for the "XOR" to work too.

Kind regards,
Duncan

**Comment by redplc** [comment]
Hello,

Sorry for late answer.

Thank you for your advice.

I looked at my code again and couldn't find any errors.
All commands are in lowercase.
The "xor" is also implemented in line 487.
Or did I miss something or not understand it?
At the end I have attached the code section again for you.

![image](https://github.com/user-attachments/assets/5a360288-3b60-440e-9ba4-712b08d19367)

**Comment by DuncanG5** [comment]
Thank you for getting back to me and your time in trying to fix it so far. 

The packages work run on my PC too but function node just defaults to the "or" gate when trying to use the "and" and "xor".

This is a simple node-red flow to explain the issue I was having.
![image (2)](https://github.com/user-attachments/assets/673cc642-4743-4a43-a14e-1b0e44969ece)

I had to alter "and" and "xor" on lines 487, 496 and 499 to be in Uppercase. As you have them with uppercases in the @redplc/node-red-redplc/nodes/redplc-function.js on lines 44 and 45. Copied.
![Screenshot 2024-07-13 150046](https://github.com/user-attachments/assets/9e0ee02c-8ec5-4011-bc9e-2e52c511dbd5)

After the correction the same code runs like you designed it too. 
![image (1)](https://github.com/user-attachments/assets/75808e31-09e7-4328-9f4b-eb8b92b539e6)

You can fix it by changing the syslib or the function.js to match each over case wise.

**Comment by redplc** [comment]
Hi Duncan,
now I've seen the error.
Thank you for pointing it out.
I have to investigate where I'm calling the getPayloadBool function.
Then I can decide where to change it.
The function node isn't actually a ladder logic element.
It's more of a function block diagram element.
But I implemented it anyway.
I'm thinking about adding a PID node as well.
If you have any suggestions, I'd be happy to incorporate them.

Best regards
Derya

**Comment by redplc** [comment]
Hi Duncan,
Thank again you for pointing it out.
New version is on npm and Node-Red.
Best regards
Derya

**Comment by DuncanG5** [comment]
Thank you so much for fixing the bug Derya, 
The PID node would be great. 
I cannot think of anything else that we would need added at the moment. 
Best regards, 
Duncan
